name: Test
on:
  push: {}

jobs:
  build_test:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: 'linux/amd64, windows/amd64'
          package: 'ipc'
          name: 'ipc'
          compress: 'true'
          dest: 'dist'
      - run: find dist
